name = "CertifiedQuantumBounds"
uuid = "fcecd4aa-10fd-48e0-9ff9-efa335504649"
version = "0.1.0"

[deps]
Arblib = "fb37089c-8514-4489-9461-98f9c8763369"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NCTSSOS = "74af9cd0-d9b7-11ea-3577-f378dad115d4"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
QMBCertify = "71df4310-1531-11eb-256d-190d0a52716f"
